dist: trusty
sudo: false
services:
  - docker
before_script:
  - docker pull ezak/yoco_neutrino_bs:20171124
env:
  global:
    - TEMPLATECONF=/home/user/poky/poky/meta-hd51/example_neutrino
script:
    - docker run -it ezak/yoco_neutrino_bs
    - echo `pwd`
    - echo `ls`
