dist: trusty
sudo: required
before_install:
  - sudo apt-get install git make gcc g++ diffstat texinfo chrpath libsdl-dev
script:
    - git clone -b rocko git://git.yoctoproject.org/poky
    - cd poky
    - git clone https://github.com/neutrino-hd/meta-neutrino.git
    - git clone https://github.com/neutrino-hd/meta-hd51.git
    - git clone https://github.com/neutrino-hd/meta-kodi.git
    - . ./oe-init-build-env build-hd51-neutrino
    - cd ..
    - cp meta-hd51/example_neutrino/local.conf.sample build-hd51-neutrino/conf/local.conf
    - cp meta-hd51/example_neutrino/bblayers.conf.sample build-hd51-neutrino/conf/bblayers.conf
    - . ./oe-init-build-env build-hd51-neutrino
    - bitbake neutrino-image
