# This references a standard debian container from the
# Docker Hub https://registry.hub.docker.com/_/debian/
# Read more about containers on our dev center
# http://devcenter.wercker.com/docs/containers/index.html
box: ubuntu
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
# services:
    # - postgres
    # http://devcenter.wercker.com/docs/services/postgresql.html

    # - mongo
    # http://devcenter.wercker.com/docs/services/mongodb.html

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
    # Steps make up the actions in your pipeline
    # Read more about steps on our dev center:
    # http://devcenter.wercker.com/docs/steps/index.html
  steps:
    - install-packages:
        packages: git python2.7=2.7.12
    - script:
      name: build neutrino
      code: |
        # create buildfolder
        apt-get update
        mkdir yocto
        cd yocto
        git clone -b rocko git://git.yoctoproject.org/poky
        cd poky
        git clone https://github.com/neutrino-hd/meta-neutrino.git
        git clone https://github.com/neutrino-hd/meta-hd51.git
        git clone https://github.com/neutrino-hd/meta-kodi.git
        export TEMPLATECONF=meta-hd51/example_kodi
        . ./oe-init-build-env build-hd51-neutrino
        bitbake neutrino-image
