box: ezak/yocto_neutrino_bs
build:
  steps:
    - script:
      name: build neutrino
      code: |
        cd /home/user/yocto/poky
        su -s /bin/bash -c "export TEMPLATECONF=meta-hd51/example_neutrino && . ./oe-init-build-env build-hd51-neutrino && bitbake neutrino-image" user
