before_install:
  - sudo apt-get install git make gcc g++ diffstat texinfo chrpath libsdl-dev
env:
  global:
    - TEMPLATECONF=/home/travis/build/Ezak91/yocto-neutrino-dayli-build/poky/meta-hd51/example_neutrino
script:
    - git clone -b rocko git://git.yoctoproject.org/poky
    - cd poky
    - git clone https://github.com/neutrino-hd/meta-neutrino.git
    - git clone https://github.com/neutrino-hd/meta-hd51.git
    - git clone https://github.com/neutrino-hd/meta-kodi.git
    - pwd
    - echo "Templateconf ist ${TEMPLATECONF}"
    - . ./oe-init-build-env build-hd51-neutrino
    - bitbake neutrino-image
